repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: poetry-check
        name: validate pyproject.toml
        entry: poetry check
        language: system
        pass_filenames: false
        files: ^pyproject\.toml$
      - id: poetry-lock
        name: check poetry.lock
        entry: poetry lock --check
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: false
      - id: nbqa-isort
        name: nbqa-isort
        entry: poetry run nbqa isort .
        language: system
        pass_filenames: false
      - id: nbqa-pycln
        entry: nbqa pycln
        name: nbqa-pycln
        entry: poetry run nbqa pycln .
        args: [--config=pyproject.toml]
        language: system
        pass_filenames: false
      - id: nbqa-black
        name: nbqa-black
        entry: poetry run nbqa black .
        language: system
        pass_filenames: false
      - id: nbqa-mypy
        name: nbqa-mypy
        entry: poetry run nbqa mypy .
        language: system
        pass_filenames: false
      - id: nbqa-flake8
        name: nbqa-flake8
        entry: poetry run nbqa flake8 .
        language: system
        pass_filenames: false
